version: '3'
services:
  app:
    container_name: CodingTestBackEnd
    restart: on-failure:4
    build:
      context: .
      dockerfile: ./Dockerfile.test.e2e
    ports:
      - '3000:3000'
    links:
      - mysql
  mysql:
    container_name: CodingTestBackEndMySQL
    image: mysql
    environment:
          MYSQL_DATABASE: appDb
          MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'