version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1

    steps:
      - checkout
      - setup_remote_docker
      - run: npm run compose:test && exit "$(git diff | wc -l)"
      - run: npm run compose:test:e2e